### ISSUE TITLE
Filter by type (vegan only / vegetarian / ...)

### ISSUE THREAD

**Issue by florianwittmann** [VeggieSailor/VeggieSailor#2]
As a user, I want to be able to filter for a specific type of restaurant. For example I want to select only vegan ones.

**Comment by bluszcz** [comment]
I am a bit new into QML / SailfishOS patterns, can you point to some good UI element which would fit? Thank you.

**Comment by florianwittmann** [comment]
Good question. I would add a PullDown Menu with a filter option. It could bring a kind of overlay similar to the jolla music player when starting to play a song. In that overlay then maybe just a normal dropdown. If you have some backend and have problems in qml frontend, I could help with another pull request :-)

**Comment by florianwittmann** [comment]
#26 implements this filter. Can you have a quick look on it?

**Comment by bluszcz** [comment]
Thank  you.
