### ISSUE TITLE
Translation of VeggieSailor

### ISSUE THREAD

**Issue by florianwittmann** [VeggieSailor/VeggieSailor#20]
As a user I like to use VeggieSailor in my local language.

-> We could use https://www.transifex.com/ for hosting and managing the translations. It's quite popular for Sailfish projects and has a free plan for open source projects.
(Example: https://www.transifex.com/projects/p/sailgrande/ )

**Comment by bluszcz** [comment]
I created account and project briefly, but don't have really now time to play with it more to finish configuration.

**Comment by bluszcz** [comment]
Ok, test if assigning of tickets works. Let me know if you need something more to setup a project for translation.

**Comment by florianwittmann** [comment]
Now you can assign me, but I can not assign myself neither delete my assigment for some task. I think you need to upgrade the group right to "write" access to give me this possibilties. Thanks!

**Comment by florianwittmann** [comment]
Okay translations project is here: https://www.transifex.com/projects/p/veggiesailor
Config for projects is nearly finished.

**Comment by bluszcz** [comment]
Ok, thanks for @florianwittmann  determination and relentless ;) during introducing me Transifex - we will be using now it to translate the project :)  https://github.com/VeggieSailor/VeggieSailor/pull/22

It would be nice also to include some short info in docs / webpage - which I will do. Thank you.

**Comment by florianwittmann** [comment]
My opinion at least finnish should be included in version 1.0. The other started languages should be also at 100% before release.

**Comment by florianwittmann** [comment]
Thanks for merging - Stupid typo ;)

**Comment by bluszcz** [comment]
Correct, yes - 1.0 harbour will include only 100% finished languages.  Your welcome and thank you for pushing me forward ;)

**Comment by florianwittmann** [comment]
The transifex project link https://www.transifex.com/projects/p/veggiesailor should also be included in openrepos description and in credits to ask for translation help :-)

**Comment by bluszcz** [comment]
Correct and I found just time for it :+1:
