### ISSUE TITLE
No new entries.

### ISSUE THREAD

**Issue by ghost** [VeggieSailor/VeggieSailor#28]
Hi,

The App doesn't update the entries, I'm missing several Entries that can be found on vegguide.org but don't appear in the App (including the whole City of Freiburg in Germany).

What could cause this? What information do you need to solve this?

**Comment by bluszcz** [comment]
What is happening when you clean a cache?

**Comment by ghost** [comment]
Doesn't change anything, I tried that. Also tried reinstall, didn't help either.
Some new info: Apperantly its only regions that don't get added, single venues are updated.

**Comment by bluszcz** [comment]
Could you please provide link to same entity in Vegguide?  Only Freiburg which I see is: http://www.vegguide.org/region/2981 and its being visible in the app.

**Comment by ghost** [comment]
Okay, I'm very irritated. The entry just showed up, after missing for at least 3 weeks...

I have no idea why, I cleared the cache (again) and now it appeared for some reason. Well, I guess that closes this issue...

Anyway, thanks for trying to help!

**Comment by bluszcz** [comment]
It is an issue in the Django backend part.
