### ISSUE TITLE
Make app jolla harbour conform

### ISSUE THREAD

**Issue by florianwittmann** [VeggieSailor/VeggieSailor#8]
Currently the app is not harbour conform - see https://harbour.jolla.com/faq
Can easily be verifed with Harbour Tools in "SailfishOS"-Tab of sdk.

**Comment by bluszcz** [comment]
I was experiment a bit with it today - changing with the name of the project - but it generated so many errors and I was not able to build it again. But its on my list... Perhaps can be split into subtasks hehe

**Comment by florianwittmann** [comment]
I will try that, have done this with one of mine projects already a few months ago.

**Comment by bluszcz** [comment]
How I can give you access to the issues?

**Comment by florianwittmann** [comment]
Good question. As contributor it should work now, but I still can not selfassign me or add labels for example.

**Comment by bluszcz** [comment]
@florianwittmann I have created a branch - if you want you can give a test

**Comment by bluszcz** [comment]
Only this is left (but this is becase it has been built in builds.merproject):

```
RPM file name
=============
ERROR [10.7.1.jolla] rpm release must contain only digits (0-9), underscores (_) and periods (.)
FAILED
```

and this:

```
Vendor check
============
WARNING [harbour-veggiesailor-0.6.5-10.7.1.jolla.armv7hl.rpm] Vendor is set to 'meego'! This is not recommended, unless your previous submissions to Harbour have the vendor set to 'meego' also. Do this only if you know what you are doing!
PASSED
```

but I guess this is also set by build environment.

I have tested against binaries here: https://github.com/bluszcz/VeggieSailor/releases/tag/0.6.5
